# Generated by Django 2.2.13 on 2020-08-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_preview',
            field=models.TextField(blank=True),
        ),
    ]
