# Generated by Django 2.2.13 on 2020-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='title',
            field=models.CharField(default='myCV', editable=False, max_length=4),
        ),
    ]
