# Generated by Django 2.2.13 on 2020-08-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_cv_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
