# Generated by Django 2.2.13 on 2020-08-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200830_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eduelement',
            name='subTitle',
            field=models.TextField(blank=True),
        ),
    ]
