# Generated by Django 2.2.13 on 2020-08-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200831_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workelement',
            name='paid',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
